export const SHIPPING_COUNTRY_ERROR_CODES = {
  ERROR_SHIPPING_COUNTRY_001: {
    message: 'SHIPPING COUNTRY NOT FOUND',
    code: 'ERROR_SHIPPING_COUNTRY_001'
  },
  ERROR_SHIPPING_COUNTRY_002: {
    message: 'SHIPPING COUNTRY NAME EXISTS',
    code: 'ERROR_SHIPPING_COUNTRY_002'
  },
  ERROR_SHIPPING_COUNTRY_003: {
    message: 'SHIPPING COUNTRY INACTIVE',
    code: 'ERROR_SHIPPING_COUNTRY_003'
  },
  ERROR_SHIPPING_COUNTRY_004: {
    message: 'SHIPPING COUNTRY ACTIVE',
    code: 'ERROR_SHIPPING_COUNTRY_004'
  },
  ERROR_SHIPPING_COUNTRY_005: {
    message: 'SHIPPING COUNTRY DATA EMPTY',
    code: 'ERROR_SHIPPING_COUNTRY_005'
  },
  ERROR_SHIPPING_COUNTRY_006: {
    message: 'SHIPPING COUNTRY NOT SUPPORT FOR SELLER',
    code: 'ERROR_SHIPPING_COUNTRY_006'
  }
}
